// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.6
// source: internal/proto/calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на получение задачи
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_internal_proto_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{0}
}

// Ответ на получение задачи
type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Arg1          float64                `protobuf:"fixed64,3,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2          float64                `protobuf:"fixed64,4,opt,name=arg2,proto3" json:"arg2,omitempty"`
	OperationTime int32                  `protobuf:"varint,5,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	DependsOn     []string               `protobuf:"bytes,6,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	UserLogin     string                 `protobuf:"bytes,7,opt,name=user_login,json=userLogin,proto3" json:"user_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_internal_proto_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *GetTaskResponse) GetArg1() float64 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *GetTaskResponse) GetArg2() float64 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *GetTaskResponse) GetOperationTime() int32 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *GetTaskResponse) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *GetTaskResponse) GetUserLogin() string {
	if x != nil {
		return x.UserLogin
	}
	return ""
}

// Запрос на отправку результата
type SubmitResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        float32                `protobuf:"fixed32,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultRequest) Reset() {
	*x = SubmitResultRequest{}
	mi := &file_internal_proto_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultRequest) ProtoMessage() {}

func (x *SubmitResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitResultRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitResultRequest) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

// Ответ на отправку результата
type SubmitResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultResponse) Reset() {
	*x = SubmitResultResponse{}
	mi := &file_internal_proto_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultResponse) ProtoMessage() {}

func (x *SubmitResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitResultResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на получение результата задачи по ID
type GetTaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultRequest) Reset() {
	*x = GetTaskResultRequest{}
	mi := &file_internal_proto_calculator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultRequest) ProtoMessage() {}

func (x *GetTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultRequest.ProtoReflect.Descriptor instead.
func (*GetTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// Ответ на получение результата задачи
type GetTaskResultResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Result        *wrapperspb.DoubleValue `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	TaskExists    bool                    `protobuf:"varint,2,opt,name=task_exists,json=taskExists,proto3" json:"task_exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultResponse) Reset() {
	*x = GetTaskResultResponse{}
	mi := &file_internal_proto_calculator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultResponse) ProtoMessage() {}

func (x *GetTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskResultResponse) GetResult() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetTaskResultResponse) GetTaskExists() bool {
	if x != nil {
		return x.TaskExists
	}
	return false
}

var File_internal_proto_calculator_proto protoreflect.FileDescriptor

const file_internal_proto_calculator_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/calculator.proto\x12\n" +
	"calculator\x1a\x1egoogle/protobuf/wrappers.proto\"\x10\n" +
	"\x0eGetTaskRequest\"\xd5\x01\n" +
	"\x0fGetTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x12\n" +
	"\x04arg1\x18\x03 \x01(\x01R\x04arg1\x12\x12\n" +
	"\x04arg2\x18\x04 \x01(\x01R\x04arg2\x12%\n" +
	"\x0eoperation_time\x18\x05 \x01(\x05R\roperationTime\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x06 \x03(\tR\tdependsOn\x12\x1d\n" +
	"\n" +
	"user_login\x18\a \x01(\tR\tuserLogin\"F\n" +
	"\x13SubmitResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x02R\x06result\"0\n" +
	"\x14SubmitResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x14GetTaskResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"n\n" +
	"\x15GetTaskResultResponse\x124\n" +
	"\x06result\x18\x01 \x01(\v2\x1c.google.protobuf.DoubleValueR\x06result\x12\x1f\n" +
	"\vtask_exists\x18\x02 \x01(\bR\n" +
	"taskExists2\x82\x02\n" +
	"\x13OrchestratorService\x12B\n" +
	"\aGetTask\x12\x1a.calculator.GetTaskRequest\x1a\x1b.calculator.GetTaskResponse\x12Q\n" +
	"\fSubmitResult\x12\x1f.calculator.SubmitResultRequest\x1a .calculator.SubmitResultResponse\x12T\n" +
	"\rGetTaskResult\x12 .calculator.GetTaskResultRequest\x1a!.calculator.GetTaskResultResponseB\x16Z\x14internal/proto;protob\x06proto3"

var (
	file_internal_proto_calculator_proto_rawDescOnce sync.Once
	file_internal_proto_calculator_proto_rawDescData []byte
)

func file_internal_proto_calculator_proto_rawDescGZIP() []byte {
	file_internal_proto_calculator_proto_rawDescOnce.Do(func() {
		file_internal_proto_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_calculator_proto_rawDesc), len(file_internal_proto_calculator_proto_rawDesc)))
	})
	return file_internal_proto_calculator_proto_rawDescData
}

var file_internal_proto_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_calculator_proto_goTypes = []any{
	(*GetTaskRequest)(nil),         // 0: calculator.GetTaskRequest
	(*GetTaskResponse)(nil),        // 1: calculator.GetTaskResponse
	(*SubmitResultRequest)(nil),    // 2: calculator.SubmitResultRequest
	(*SubmitResultResponse)(nil),   // 3: calculator.SubmitResultResponse
	(*GetTaskResultRequest)(nil),   // 4: calculator.GetTaskResultRequest
	(*GetTaskResultResponse)(nil),  // 5: calculator.GetTaskResultResponse
	(*wrapperspb.DoubleValue)(nil), // 6: google.protobuf.DoubleValue
}
var file_internal_proto_calculator_proto_depIdxs = []int32{
	6, // 0: calculator.GetTaskResultResponse.result:type_name -> google.protobuf.DoubleValue
	0, // 1: calculator.OrchestratorService.GetTask:input_type -> calculator.GetTaskRequest
	2, // 2: calculator.OrchestratorService.SubmitResult:input_type -> calculator.SubmitResultRequest
	4, // 3: calculator.OrchestratorService.GetTaskResult:input_type -> calculator.GetTaskResultRequest
	1, // 4: calculator.OrchestratorService.GetTask:output_type -> calculator.GetTaskResponse
	3, // 5: calculator.OrchestratorService.SubmitResult:output_type -> calculator.SubmitResultResponse
	5, // 6: calculator.OrchestratorService.GetTaskResult:output_type -> calculator.GetTaskResultResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_calculator_proto_init() }
func file_internal_proto_calculator_proto_init() {
	if File_internal_proto_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_calculator_proto_rawDesc), len(file_internal_proto_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_calculator_proto_goTypes,
		DependencyIndexes: file_internal_proto_calculator_proto_depIdxs,
		MessageInfos:      file_internal_proto_calculator_proto_msgTypes,
	}.Build()
	File_internal_proto_calculator_proto = out.File
	file_internal_proto_calculator_proto_goTypes = nil
	file_internal_proto_calculator_proto_depIdxs = nil
}
